### ISSUE TITLE
[Feature Request] Separate modules per package

### ISSUE THREAD

**Issue by alexadhy** [kokizzu/gotro#5]
Just a friendly tip, currently this package pulled literal metric tons of dependencies, it would be better if each Letter directories have its own go.mod.

**Comment by dhiemaz** [comment]
Nice feedback, what do you think @kokizzu ?

**Comment by kokizzu** [comment]
sure :3

**Comment by kokizzu** [comment]
umm.. but this would not be fallback compatible
everyone that has gotro on their go.mod have to change everything

**Comment by kokizzu** [comment]
tested with simple example that only import `gotro/L`

```
package b
import "github.com/kokizzu/gotro/L"
func main() {
   L.Describe("ayaya")
}
```

and the `go mod tidy` result is only using:

```
module b

go 1.17

require github.com/kokizzu/gotro v1.1018.858

require (
  github.com/fatih/color v1.10.0 // indirect
  github.com/kr/pretty v0.2.1 // indirect
  github.com/kr/text v0.2.0 // indirect
  github.com/mattn/go-colorable v0.1.8 // indirect
  github.com/mattn/go-isatty v0.0.12 // indirect
  github.com/op/go-logging v0.0.0-20160315200505-970db520ece7 // indirect
  golang.org/x/sys v0.0.0-20210823070655-63515b42dcdf // indirect
)
```

the database and other stuff not downloaded because it wasn't used
